### ISSUE TITLE
[Me Conta ? ] Campo nome aceita espaços vazios

### ISSUE THREAD

**Issue by AlexandreTI-AUT** [MeConta/me-conta-frontend#24]
Campo nome aceita espeços vazios.

**Steps para reprodução:**

1- Acessar https://me-conta-frontend.herokuapp.com/criar-conta
2- No campo nome clicar na tecla espaço 
3- Preencher os demais campos e clicar em Cadastrar.

**Resultado atual:** Campo nome permite espaços vazios

**Resultado experado:** Não Permitir espaços vazios

Evidência em anexo:

https://user-images.githubusercontent.com/76537519/136074469-352021c8-fec3-499d-8aac-8fc9e694e7f7.mov

<img width="850" alt="Screen Shot 2021-10-05 at 14 38 50" src="https://user-images.githubusercontent.com/76537519/136074672-c45cbc21-dcf4-4449-9d87-19d9181199e2.png">

**Comment by AlexandreTI-AUT** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pagina Criar Conta](https://trello.com/c/uqqcmCqc/2-pagina-criar-conta)

**Comment by renanluizz** [comment]
A correção foi feita e já está disponível no heroku :)
